apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd_vim-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd_vim
      version: green
  template:
    metadata:
      labels:
        app: httpd_vim
        version: green
    spec:
      containers:
      - name: bankapp
        image: yashasdocker/httpd_vim # Adjust the image tag for the green version
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Test@123
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
